(function(render) {
  const Helpers = window.FollowBackApp.Helpers;
  render.renderTable = function(dataArray) {
    const tbody = document.getElementById('dynamicTableBody');
    if (!tbody) return;
    tbody.innerHTML = '';
    dataArray.forEach((row, idx) => {
      const tr = document.createElement('tr');
      tr.setAttribute('data-index', idx);
      const tdAvatar = document.createElement('td');
      const img = document.createElement('img');
      img.src = row.avatar;
      img.alt = 'avatar';
      img.className = 'avatar-img';
      tdAvatar.appendChild(img);
      tr.appendChild(tdAvatar);
      const tdUser = document.createElement('td');
      const nameDiv = document.createElement('div');
      nameDiv.className = 'user-name';
      nameDiv.title = row.displayName || '';
      nameDiv.textContent = row.displayName || '';
      const handleDiv = document.createElement('div');
      handleDiv.className = 'user-handle';
      handleDiv.title = row.handle || '';
      handleDiv.textContent = row.handle || '';
      tdUser.appendChild(nameDiv);
      tdUser.appendChild(handleDiv);
      tr.appendChild(tdUser);
      const tdFollowers = document.createElement('td');
      tdFollowers.className = 'stats-number';
      tdFollowers.textContent = Helpers.formatNumber(row.followers) || '';
      tr.appendChild(tdFollowers);
      const tdFollowing = document.createElement('td');
      tdFollowing.className = 'stats-number';
      tdFollowing.textContent = Helpers.formatNumber(row.following) || '';
      tr.appendChild(tdFollowing);
      const tdLikes = document.createElement('td');
      tdLikes.className = 'stats-number';
      tdLikes.textContent = Helpers.formatNumber(row.likes) || '';
      tr.appendChild(tdLikes);
      const tdDate = document.createElement('td');
      let dateVal = row.date;
      if (dateVal && typeof dateVal === 'string' && dateVal.includes('-')) dateVal = Helpers.formatDate(dateVal);
      tdDate.textContent = dateVal || '';
      tr.appendChild(tdDate);
      const tdCheck = document.createElement('td');
      const chk = document.createElement('input');
      chk.type = 'checkbox';
      chk.className = 'table-checkbox';
      chk.checked = !!row.followBack;
      tdCheck.appendChild(chk);
      tr.appendChild(tdCheck);
      tbody.appendChild(tr);
    });
  };
})(window.FollowBackApp.Render = window.FollowBackApp.Render || {});